server:
  http:
    name: upload-svc
    host: 0.0.0.0
    port: ${SERVER_PORT}
    middlewares:
      prometheus: false
      metrics: true
      shedding: true
      log: true

aws-s3:
  bucket-region: ${AWS_BUCKET_REGION}
  bucket-name: ${AWS_BUCKET_NAME}
  bucket-access-key: ${AWS_BUCKET_ACCESS_KEY}
  bucket-secret-key: ${AWS_BUCKET_SECRET_KEY}
  cdn-url: "${AWS_BUCKET_CDN_URL}"
  public-id: "${AWS_BUCKET_PUBLIC_ID}"
  private-key: "${AWS_BUCKET_PRIVATE_KEY}"
  allow-exts:
    - "*"
